{% set name = "apache-airflow-providers-daskexecutor" %}
{% set version = "1.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/apache-airflow-providers-daskexecutor-{{ version }}.tar.gz
  sha256: 0bce30e0332d81bb43374dd15c2eab2be4cf8eff6ad7686c3258a94a5e269fc5

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools >=67.2.0,<68.0.0
    - pip
  run:
    - python >=3.8
    - apache-airflow >=2.5.0
    - cloudpickle >=1.4.1
    - dask-core >=2.9.0,!=2022.10.1,!=2023.5.0
    - distributed >=2.11.1,!=2023.5.0

test:
  imports:
    - airflow.providers.daskexecutor
    - airflow.providers.daskexecutor.executors
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://airflow.apache.org/
  summary: Provider for Apache Airflow. Implements apache-airflow-providers-daskexecutor package
  license: Apache-2.0
  license_file:
    - LICENSE
    - NOTICE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-daskexecutor/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
